### ISSUE TITLE
Nit: please make java method names begin with lowercase

### ISSUE THREAD

**Issue by jessethouin** [GoogleCloudPlatform/dataflow-sample-applications#62]
https://github.com/GoogleCloudPlatform/dataflow-sample-applications/blob/be9e861d37076b92fdb28361b8d0272db6603be3/timeseries-streaming/timeseries-java-applications/TimeSeriesMetricsLibrary/src/main/java/com/google/dataflow/sample/timeseriesflow/metrics/utils/StatisticalFormulas.java#L31

https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html - "Methods should be verbs, in mixed case with the first letter lowercase, with the first letter of each internal word capitalized."

There may be other examples throughout the codebase, or I got lucky. Super minor issue, but impedes readability.

**Comment by jessethouin** [comment]
I forgot to mention...THANK YOU for your work on this!!

**Comment by dsdinter** [comment]
Thanks for picking this up @jessethouin, it should be fixed now.
