### ISSUE TITLE
 gradle run_example failed failed for Sending a stream of examples to PubSub

### ISSUE THREAD

**Issue by sreecharanmanne2000** [GoogleCloudPlatform/dataflow-sample-applications#87]
The data sent to PubSub is parsed into JSON format is failing when executed this example_4 in timeseries_java_applications folder's README file.           
                                                                                                      
`./gradlew run_example --args='--withOutliers=true --pubSubTopicForTSAccumOutputLocation=projects/<your-project>/topics/outlier-detection'`

**Error  :**

`FAILURE: Build failed with an exception.

* What went wrong:
Problem configuring task :SyntheticExamples:run_example from command line.
> Unknown command-line option '--pubSubTopicForTSAccumOutputLocation'.

* Try:
Run gradlew help --task :SyntheticExamples:run_example to get task usage details. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1s`

**Comment by rezarokni** [comment]
Ran a test with latest master and command option was working.
